### ISSUE TITLE
server_commandline does not accept arguments

### ISSUE THREAD

**Issue by diggit** [quarnster/SublimeGDB#111]
As title says, I was not able to add arguments to "sublimegdb_server_commandline" in my project config:
```yaml
"settings":
    {
        "sublimegdb_gdb_timeout": 3,
        "sublimegdb_commandline": "arm-none-eabi-gdb --interpreter=mi *.elf",
        "sublimegdb_workingdir": "${project_path:.}",
        "sublimegdb_server_workingdir": "${project_path:.}",
        "sublimegdb_server_commandline": "openocd -f {project_path:openocd.cfg}",
        //"sublimegdb_exec_cmd": "-exec-continue",
        //"sublimegdb_load_cmd": "-target-download",
        //"sublimegdb_attach_cmd" : "-gdb-set target-async 1",
        "sublimegdb_run_after_init": false,
    },
```

throws error:
```
Will write debug info to file: stdout
Running: arm-none-eabi-gdb --interpreter=mi *.elf
In directory: /home/diggit/dev/eforce/ECUS/code/.
gdb_server_cmd: openocd -f {project_path:openocd.cfg}gdb_server_dir: /home/diggit/dev/eforce/ECUS/code/.gdb_server_dir: FalseTraceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1036, in run_
    return self.run()
  File "/home/diggit/.config/sublime-text-3/Packages/SublimeGDB/sublimegdb.py", line 1596, in run
    self.launch()
  File "/home/diggit/.config/sublime-text-3/Packages/SublimeGDB/sublimegdb.py", line 1673, in launch
    gdb_server_process = subprocess.Popen(gdb_server_cmd, shell=gdb_server_shell, cwd=gdb_server_dir, env=gdb_env)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'openocd -f {project_path:openocd.cfg}'
```

How am I supposed to tell `openocd` whete its' config file is? Do I have to wrap it into script?

**Comment by brainelectronics** [comment]
I'm currently using this, as I'm also not able to get it running with the `sublimegdb_server_commandline` option.

`"sublimegdb_commandline": "st-util & arm-none-eabi-gdb --interpreter=mi --args /example.elf",
`

**Comment by diggit** [comment]
Oh, I totally  forgot about this open issue. I am not using this plugin anymore (switched to vscode for embedded). Seeing last commit from Jan 2019, I guess this plugin is not actively developed anymore. @brainelectronics do you want to keep this issue opened?

**Comment by brainelectronics** [comment]
fine for me to close the issue @diggit
